const MODEL_EMBEDDINGS = 'text-embedding-ada-002';
const MODEL_COMPLETIONS = 'text-davinci-003';
const INDEX_DIMENSIONS = 1536;
const PINECONE_RELEVANCE_THRESHOLD = 0.7;
const MAX_CONTEXT_TOKENS = 1500;

module.exports = {
  MODEL_EMBEDDINGS,
  MODEL_COMPLETIONS,
  INDEX_DIMENSIONS,
  PINECONE_RELEVANCE_THRESHOLD,
  MAX_CONTEXT_TOKENS,
};
